import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Github } from "lucide-react";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "flex flex-col min-h-screen antialiased min-w-screen",
          geistMono.variable,
          geistSans.variable
        )}
      >
        <main className="flex flex-col flex-1">
          <div className="font-mono container mx-auto">{children}</div>
          <footer className="mt-auto p-5 border-t border-gray-300 w-full flex gap-[24px] flex-wrap font-mono items-center justify-center">
            <a
              className="flex items-center gap-2 hover:underline hover:underline-offset-4"
              href="https://github.com/kiShubham"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Github />
              github
            </a>
          </footer>
        </main>
      </body>
    </html>
  );
}
